- src/index.js
`await` inside a loop is almost always an error!
Docs here: https://eslint.org/docs/rules/no-await-in-loop
> Add no-await-in-loop rule

- package.json
- prettier-config.js
- yarn.lock
Replace the Prettier configuration distributed by this repository with a shared configuration (Prettier added support for shared configs in 1.17.0.)
Using the configuration distributed by this repository is now deprecated and will log a deprecation notice.
> feat: use shared prettier configuration

- src/config/recommended.js
- src/config/typescript.js
This changeset forces consumers to specify the `.json` extension when
importing JSON files. Because ESLint merges arrays positionally (really
unfortunate, confusing behavior) it's really easy to end up with
unexpected ESLint configuration when specifying arrays of extensions
like we're doing here. This change makes it unnecessary to override most
`eslint-plugin-import` settings, allowing us to simplify our config and
avoid this footgun.
We specify the `.json` extension in most places already, and adding it
is a very quick fix in the places where we don't, so this seems like an
unobtrusive change.
> feat: disallow implicit JSON file imports

- src/config/ops.js
- src/config/recommended.js
Currently, the `eslint-plugin-import` configuration makes a best-effort
attempt at accomodating two project layouts: One that uses
`babel-plugin-local-modules` to add the `local_modules` directory to the
module lookup path, and one that relies on packages in `src/*` being
somehow included in the module lookup (historically, we did this by
symlinking directories in `src/{name}` into `src/node_modules/{name}`).
In ops apps, this works but 1) assumes you're using
`babel-plugin-local-modules` (which is usually true, but not a given),
and 2) introduces any directory at the root of the project into
`eslint-plugin-import`'s module resolution algorithm, which means it may
not catch some errors. In garbanzo, when we switched to
[`babel-plugin-module-resolver`](https://github.com/tleunen/babel-plugi …
> fix: remove resolver settings

- src/config/recommended.js
We've long had the undesired ability to introduce newlines within an
import group. This changeset prohibits newlines within an import group
and results in the following example diff:
```diff
import _ from 'underscore';
-
import geomoment from 'geomoment';
-
import fulfillmentDayFactory from 'goodeggs-fulfillment-options-sdk/fulfillment_day/factory';
```
Closes https://github.com/goodeggs/best-practices/issues/234.
> fix: don't allow newlines within import groups

- src/config/recommended.js
This fixable rule prevents developers from adding `index` in imports;
this only impacts extensions passed via `settings['import/extensions']`.
Documentation: https://github.com/benmosher/eslint-plugin-import/blob/112a0bf442e52b25cd7029a9905df2508e191ac1/docs/rules/no-useless-path-segments.md
> feat: prevent useless `index` in imports

- package.json
- src/config/recommended.js
- yarn.lock
This rule prevents developers from using `eslint-disable` without
specifying specific rules to disable.
Documentation here: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/4d5f5cb681250e7dbafa32c5c2e95737e80b7233/docs/rules/no-abusive-eslint-disable.md
> feat: prevent abusive eslint-disables

- src/config/recommended.js
This rule reports false positives and will soon be removed from the
`eslint:recommended` ruleset. For more info, see:
https://github.com/eslint/eslint/issues/11899#issuecomment-541714523
> fix: disable require-atomic-updates rule

- src/config/typescript.js
Historically, limitations on what you can do in `overrides` forced us to
enable TypeScript rules on all files, regardless of filetype, in
projects that use the `plugin:goodeggs/typescript` preset. This is
mostly fine, except rules like
`@typescript-eslint/explicit-function-return-type` report rule
violations in `.js` and `.jsx` files, where they're impossible to fix.
As of ESLint 6, you can use `extends` in `overrides` entries. This
changeset updates the preset to only enable the TypeScript parser and
rules on `.ts` and `.tsx` files.
Closes #200.
> fix: only enable TypeScript rules on `.ts`/`.tsx` files

- src/config/recommended.js
- src/config/typescript.js
Previously, the TypeScript preset allowed you to ignore unused arguments
to functions by prefixing them with an underscore.
5b28aa6910b83e2eda37844c77a8b52d516e07db revealed that we apply this
rule inconsistently depending on whether or not you enable the
TypeScript configuration.
This changeset fixes the inconsistency, applying the rule to both JS and
TS files with identical options.
> fix: use identical no-unused-vars config in JS+TS configs

- package.json
- src/config/typescript.js
- yarn.lock
This updates our TypeScript configuration to force developers to only
use string expressions inside template literals. Anecdotally, I've seen
us make this mistake several times in the Good Eggs codebase.
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/restrict-template-expressions.md
> feat: enforce string types in template literals

- src/config/recommended.js
This changeset enables various (hopefully uncontroversial) rules from
`eslint-plugin-unicorn`:
https://github.com/sindresorhus/eslint-plugin-unicorn/tree/master/docs/rules
There are probably some others we want to enable, but this gets us started.
> feat: enable various eslint-plugin-unicorn rules

- src/config/recommended.js
This rule sometimes inserts invalid changes into files (seemingly, this only affects TS files).
> fix: disable unicorn/custom-error-definition

- src/config/typescript.js
This changeset enables `return-await`, which was added in
`@typescript-eslint/eslint-plugin@2.9.0`. This reflects our current best
practices (see: https://github.com/goodeggs/best-practices/blob/a6dc869deb69d3e1d0bb6a994279a20b239d5995/javascript/asynchronous-programming.md#avoid-return-await).
Rule documentation: https://github.com/typescript-eslint/typescript-eslint/blob/3ddf1a2a0fb0b7863dee048913053f2c59f8283e/packages/eslint-plugin/docs/rules/return-await.md
> feat: restrict return/await in TypeScript source

- src/config/typescript.js
This change enables the `@typescript-eslint/restrict-plus-operands`
rule, which disallows adding values of two different types. This is
generally a developer error and if intentional, it's easy to make your
code more explicit by either parsing the string to a numeric, or calling
formatting the number to a string (which forces you to think about
how the number should be displayed--something you should be doing,
anyway).
Rule docs: https://github.com/typescript-eslint/typescript-eslint/blob/3ddf1a2a0fb0b7863dee048913053f2c59f8283e/packages/eslint-plugin/docs/rules/restrict-plus-operands.md
> feat: restrict types that can be used in plus operations in TS

- src/config/typescript.js
This changeset enables `no-extra-non-null-assertion`, which was added in
`@typescript-eslint/eslint-plugin@2.9.0`.
Rule documentation: https://github.com/typescript-eslint/typescript-eslint/blob/3ddf1a2a0fb0b7863dee048913053f2c59f8283e/packages/eslint-plugin/docs/rules/no-extra-non-null-assertion.md
> feat: prevent extraneous non-null assertions in TS

- src/config/recommended.js
In https://github.com/goodeggs/eslint-plugin-goodeggs/commit/40923b5, we accidentally removed the `camelcase` rule from the `recommended` config. This was obscured by the fact that we have a separate TS-specific camelcase rule enabled for TS files and we have a custom-configured `camelcase` enabled in the `ops` config.
Note: this rule is already disabled in the `typescript` config to avoid having redundant rules.
> fix: re-add accidentally removed camelcase rule to recommended config

- src/config/mocha.js
This is enabled in `mocha/recommended` (as a warn). This seems overly restrictive and contradicts our best practices, e.g. when configuring default stubs whose behavior individual tests can override, or when stubbing the clock - erroring when the suite happens to currently have only one test seems unnecessary. This ends up requiring unnecessary refactoring when adding additional tests later.
> feat: disable mocha/no-hooks-for-single-case

- .travis.yml
We speculate that a former engineer accidentally used their personal creds here. They were also set via the UI for some reason, whereas we usually include them in `.travis.yml`.
> ci: re-encrypt NPM_AUTH token

- .npmrc
- .travis.yml
- README.md
- package.json
See https://goodeggs.atlassian.net/wiki/spaces/ENG/pages/459833453/Using+NPM+and+Yarn.
- Travis CI doesn't allow interpolation of env vars under `api_token`, so that wasn't working at all
- Instead, encrypt an API token ([this type](https://docs.npmjs.com/about-authentication-tokens)) and include it directly
- Explicitly specify public registry in an `.npmrc` file, since our current setup at Good Eggs is to have folks have an `~/.npmrc` that defaults to our private registry
- Explicitly specify public registry in `package.json#publishConfig`, since our current setup at Good Eggs is to have folks have an `~/.npmrc` that defaults to our private registry
- Document how to release a version in the README
- Use built-in `skip` feature for deploy step instead of echoing some stuff
> chore: configure npm/yarn per latest standard, fix publishing from CI

- package.json
I published a bump of prerelease versions under the default `latest` tag (e.g. `10.0.1-test.8`) a few weeks ago. This just publishes a clean release for cleanliness.
> release: v10.1.0

- package.json
- src/config/react.js
This PR disables the react/jsx-no-bind rule
as a result of this ADR: https://github.com/goodeggs/marketplace-mobile-app/pull/217/files
- set jsx-no-bind to off
- v10.2.0
> turn off jsx-no-bind rule

- package.json
- src/config/mocha.js
This got bubbled up [here](https://github.com/goodeggs/garbanzo/pull/6853)
- Override default behavior of throwing logging an error instead of a warm when `mocha/no-exclusive-test` is violated
> chore:throw error when no exclusive test violation

- CHANGELOG.md
- package.json
- src/config/typescript.js
- yarn.lock
* Upgrade `@typescript-eslint/eslint-plugin` to the latest version, 4.6.1. (This was motivated by the rule change below, but seeing as we're two major versions behind, it seems like a good upgrade anyway.) (3dde9740c0c4436c6ece554dae3a3178fea53744)
* Change the [`@typescript/eslint/ban-ts-comment`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-ts-comment.md#allow-with-description) rule to have the 'allow-with-description' option for `@ts-ignore`. This is so we can stop doing [this](https://github.com/goodeggs/marketplace-mobile-app/search?q=%27eslint-disable-next-line+%40typescript-eslint%2Fban-ts-comment%27&unscoped_q=%27eslint-disable-next-line+%40typescript-eslint%2Fban-ts-comment%27) and …
> Upgrade TypeScript plugin, change 'ban-ts-comment' rule

- src/config/recommended.js
We don't want to use globals – see https://github.com/goodeggs/best-practices/pull/225.
The `no-implicit-globals` rule does not really help enforce not using globals, but it catches mistakes such as accidentally overwriting built-in globals (e.g. `Array`, `document`, `alert`, `name`) and assigning to declared read-only globals (e.g. using the eslint `/* global foo:readonly */` syntax).
Closes https://github.com/goodeggs/standards-and-best-practices/issues/51.
🍐 with @serhalp
> enable no-implicit-globals eslint rule

- package.json
- src/config/recommended.js
We've intended to configure `no-unused-vars` and `@typescript-eslint/no-unused-vars` to allow unused variables with a `_` prefix. However, the rule has a separate pattern option for "variables" (excludes arguments for some reason) and "arguments". See https://eslint.org/docs/rules/no-unused-vars.
We were only actually configuring the args option. The comment above it even stated that it ended to enable it for both.
Example of what currently isn't allowed but should be:
```js
const [_unusedFirst, ...theGoodStuff] = arr;
const {...eww: _unusedKey, ...theGoodStuff} = obj;
```
I don't believe this requires a S&BP Issue since I believe this is just a misconfiguration.
(Note: our typescript rule config reads from the base eslint rule config, so no need to update this in two places.)
> fix: actually allow unused vars with _ prefix

- yarn.lock
There's something weird going on with how this repo is set up to use itself to lint its own source that results in it frequently ending up in this state. :(
I'll look into how to fix it, but committing this now to unblock failing Dependabot PRs and such.
> chore: commit uncommitted changes to yarn.lock

- package.json
- src/config/typescript.js
We follow the React community convention of using PascalCase for all React components, even "functional components", which are actually functions, even though this goes against the more general "use camelCase for functions" rule.
Unfortunately, there is no way to configure this exception specifically for React functional components, so just allow both camelCase and PascalCase for all functions :(.
See https://github.com/typescript-eslint/typescript-eslint/issues/2607.
I broke this in https://github.com/goodeggs/eslint-plugin-goodeggs/pull/597.
> fix: re-allow PascalCase for React functional components

- src/config/recommended.js
Closes https://github.com/goodeggs/best-practices/issues/236.
This rules prevents anonymous functions in default exports. (Anonymous arrays, call expressions, literals and objects are still allowed).
Not allowed:
```js
export default function({ids, logger}) { /* ... */ }
```
Allowed:
```js
export default function findByIds({ids, logger}) { /* ... */ }
```
> Add import/no-anonymous-default-export rule

- .eslintrc.js
- CHANGELOG.md
- package.json
- src/config/typescript.js
The Standards & Best Practices Guild decided a few months ago to adopt some proposed changes to the @typescript-eslint/strict-boolean-expressions eslint rule: https://github.com/goodeggs/standards-and-best-practices/issues/317.
This PR introduce those changes as a minor version
Added **@typescript-eslint/strict-boolean-expressions** eslint rule
None
Roll back usual
> Eslint set strict boolean expressions #179858055

- CHANGELOG.md
- src/config/typescript.js
Added Typescript rule that forbids the `I` prefix for interface type names, as described in story #180070491
Merging into `v13` branch to be released a single major version along with other changes later.
> Added Typescript rule for naming interfaces.

- CHANGELOG.md
- src/config/recommended.js
Disabled rules that encourage poor type coverage. Others simply conflict with other Good Eggs standards and best practices:
- `lodash/chaining`
- `lodash/identity-shorthand`
- `lodash/prefer-compact`
- `lodash/prefer-wrapper-method`
- `lodash/prefer-get`
- `lodash/prefer-is-nil`
- `lodash/prefer-lodash-chain`
- `lodash/prefer-startswith`
> Disabled rules that encourage poor type coverage (lodash/*)

- CHANGELOG.md
- src/config/typescript.js
Added rule `@typescript-eslint/explicit-function-return-type` with `allowExpressions` set to `true`.
We decided to modify this rule's configuration at the 02/01/2022 Standards & Best Practices Guild meeting.
(We then later realized we had accidentally removed this rule in v11. This is therefore restoring a relaxed version of it.)
> Added rule @typescript-eslint/explicit-function-return-type

- CHANGELOG.md
- package.json
This includes these changes:
- https://github.com/goodeggs/eslint-plugin-goodeggs/pull/885
- https://github.com/goodeggs/eslint-plugin-goodeggs/pull/886
- https://github.com/goodeggs/eslint-plugin-goodeggs/pull/887
- https://github.com/goodeggs/eslint-plugin-goodeggs/pull/893
I made this a major release because https://github.com/goodeggs/eslint-plugin-goodeggs/pull/887 is technically breaking, but it's actually fixing an accidental regression, so it's fuzzy.
> release: v14.0.0

- package.json
- src/config/recommended.js
Since the convention is to name the file the same as the module name, and we don't control what NPM module names are called (and they're usually in kebab-case), disable the `unicorn/filename-case` rule for `.d.ts` files.
> fix(config/recommended): ignore *.d.ts for filename-case rule

- CHANGELOG.md
- package.json
- src/config/recommended.js
- yarn.lock
In https://github.com/goodeggs/eslint-plugin-goodeggs/pull/987 I tried to configure a new rule.
Unfortunately, I got two things wrong:
1. awful typo in my `reduce()`... I wasn't actually spreading the accumulator, so the result was just the last extension (`{tsx: 'never'}`) 🤦
2. the rule is poorly documented - I had assumed that if you don't specify a 'default' behavior ('always' or 'never', second arg), but only an object of extension-specific configs, then the rule would not apply 'by default' to all other extensions; it turns out that's not how it works at all, and there's no way to simply not enforce anything for other extensions (or any given extension). So I just configured it to require extensions on everything other than JS/JSX/TS/TSX source files.
I'll release this as a patch, …
> fix: correctly configure new import/extensions rule
